version: "3.5"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: merqueo-php
    container_name: merqueo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./merqueo-demo:/var/www
    networks:
      - merqueo
  db:
    image: mysql:5.7
    container_name: merqueo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql/mysql-data:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - merqueo

  nginx:
    image: nginx:alpine
    container_name: merqueo-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./merqueo-demo:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - merqueo

networks:
  merqueo:
    driver: bridge